package com.musicweb.constant;

public interface DisplayConstant {
	int HOME_PAGE_NEW_SONG_SIZE = 5;
	int HOME_PAGE_NEW_ALBUM_SIZE = 5;
	int HOME_PAGE_RANK_SIZE = 5;
	int RANK_PAGE_RANK_SIZE = 20;
	int SIGNER_PAGE_SINGER_SIZE = 10;
	int ALBUM_PAGE_ALBUM_SIZE = 10;
	int ALBUM_INFO_PAGE_SONG_SIZE = 20;
	int SINGER_INFO_PAGE_SONG_SIZE = 10;
	int SINGER_INFO_PAGE_ALBUM_SIZE = 5;
	int SEARCH_PAGE_SONG_SIZE = 10;
	int SEARCH_PAGE_ALBUM_SIZE = 10;
	int SEARCH_PAGE_SINGER_SIZE = 10;
}
